services:
  nginx:
    image: docker.io/nginx:stable
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "9000:80"
